dataframe <- read.csv("Movies2016.csv",stringsAsFactors=TRUE,header = TRUE)
library(ggplot2)
dataframe$Number.of.Theaters <- as.numeric(dataframe$Number.of.Theaters) 
hist(dataframe$Opening.Gross.Sales....millions.,main="Histogram of Opening Gross Sales",xlab="Opening Gross Sales in Millions",ylab="Frequency")
summary(dataframe)
hist(dataframe$Total.Gross.Sales....millions.,main="Histogram of Total Gross Sales",xlab="Total Gross Sales in Millions",ylab="Frequency")
hist(dataframe$Number.of.Theaters,main="Histogram of Number of Theaters",xlab="Number of theaters",ylab="Frequency")
hist(dataframe$Weeks.in.Release,main="Histogram of Weeks in release",xlab="Weeks in release",ylab="Frequency")
ggplot(dataframe, aes(x=Opening.Gross.Sales....millions., y=Total.Gross.Sales....millions.)) + geom_point()
ggplot(dataframe, aes(x=Number.of.Theaters, y=Total.Gross.Sales....millions.)) + geom_point()
ggplot(dataframe, aes(x=Weeks.in.Release, y=Total.Gross.Sales....millions.)) + geom_point() 
