set.seed(1234)
dataframe <- read.csv("Movies2016.csv",stringsAsFactors=TRUE,header = TRUE)
library(ggplot2)
dataframe$Number.of.Theaters <- as.numeric(dataframe$Number.of.Theaters) 
h<-hist(dataframe$Opening.Gross.Sales....millions.,main="Histogram of Opening Gross Sales",xlab="Opening Gross Sales in Millions",ylab="Frequency")
text(h$mids,h$counts,labels=h$counts, adj=c(0.5, -0.5))
h1<-hist(dataframe$Total.Gross.Sales....millions.,main="Histogram of Total Gross Sales",xlab="Total Gross Sales in Millions",ylab="Frequency")
text(h1$mids,h1$counts,labels=h1$counts, adj=c(0.5, -0.5))
h2<-hist(dataframe$Number.of.Theaters,main="Histogram of Number of Theaters",xlab="Number of theaters",ylab="Frequency")
text(h2$mids,h2$counts,labels=h2$counts, adj=c(0.5, -0.5))
h3<-hist(dataframe$Weeks.in.Release,main="Histogram of Weeks in release",xlab="Weeks in release",ylab="Frequency")
text(h3$mids,h3$counts,labels=h3$counts, adj=c(0.5, -0.5))
ggplot(dataframe, aes(x=Opening.Gross.Sales....millions., y=Total.Gross.Sales....millions.)) + geom_point()
ggplot(dataframe, aes(x=Number.of.Theaters, y=Total.Gross.Sales....millions.)) + geom_point()
ggplot(dataframe, aes(x=log(Weeks.in.Release), y=log(Total.Gross.Sales....millions.))) + geom_point() 

